base_url: https://jsonplaceholder.typicode.com
environments:
  prod: https://jsonplaceholder.typicode.com
  staging: https://staging.example.com
auth:
  headers:
    Authorization: Bearer dummy_token
endpoints:
  - method: GET
    path: posts
    expected_status: 200
    expected_keys: ["id", "title", "body", "userId"]
    params:
      userId: 1    
  - method: POST
    path: posts
    payload: { "title": "foo", "body": "bar", "userId": 1 }
    expected_status: 201
    expected_keys: ["id", "title", "body", "userId"]
  - method: PUT
    path: posts/1
    expected_status: 200
    payload: { "title": "foo", "body": "bar", "userId": 1 }
    expected_keys: ["id", "title", "body", "userId"]
  - method: DELETE
    path: posts/1
    expected_status: 200  # May need to be 204, jsonplaceholder returns 200 whereas other RESTful APIs return 200
    expected_keys: []